const std = @import("std");

const libnfs_sources = [_][]const u8{
    "mount/libnfs-raw-mount.c",
    "mount/mount.c",
    "nfs/libnfs-raw-nfs.c",
    "nfs/nfs.c",
    "nfs/nfsacl.c",
    "nfs4/libnfs-raw-nfs4.c",
    "nfs4/nfs4.c",
    "nlm/libnfs-raw-nlm.c",
    "nlm/nlm.c",
    "nsm/libnfs-raw-nsm.c",
    "nsm/nsm.c",
    "portmap/libnfs-raw-portmap.c",
    "portmap/portmap.c",
    "rquota/libnfs-raw-rquota.c",
    "rquota/rquota.c",
    "lib/init.c",
    "lib/libnfs.c",
    "lib/libnfs-sync.c",
    "lib/libnfs-zdr.c",
    "lib/multithreading.c",
    "lib/nfs_v3.c",
    "lib/nfs_v4.c",
    "lib/pdu.c",
    "lib/socket.c",
};

const config_values = .{
    .HAVE_ARPA_INET_H = 1,
    .HAVE_CLOCK_GETTIME = 1,
    .HAVE_DLFCN_H = 1,
    .HAVE_FUSE_H = 1,
    .HAVE_INTTYPES_H = 1,
    .HAVE_MEMORY_H = 1,
    .HAVE_NETDB_H = 1,
    .HAVE_NETINET_IN_H = 1,
    .HAVE_NETINET_TCP_H = 1,
    .HAVE_NET_IF_H = 1,
    .HAVE_POLL_H = 1,
    .HAVE_SOCKADDR_STORAGE = 1,
    .HAVE_STDINT_H = 1,
    .HAVE_STDLIB_H = 1,
    .HAVE_STRINGS_H = 1,
    .HAVE_STRING_H = 1,
    .HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC = 1,
    .HAVE_SYS_IOCTL_H = 1,
    .HAVE_SYS_SOCKET_H = 1,
    .HAVE_SYS_STATVFS_H = 1,
    .HAVE_SYS_STAT_H = 1,
    .HAVE_SYS_SYSMACROS_H = 1,
    .HAVE_SYS_TIME_H = 1,
    .HAVE_TIME_H = 1,
    .HAVE_SYS_TYPES_H = 1,
    .HAVE_SYS_VFS_H = 1,
    .HAVE_TALLOC_TEVENT = 1,
    .HAVE_UNISTD_H = 1,
    .HAVE_UTIME_H = 1,
};

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const libnfs = b.addStaticLibrary(.{
        .name = "nfs",
        .target = target,
        .optimize = optimize,
    });

    const libc = b.dependency("libc", .{
        .target = target,
        .optimize = optimize,
    });

    const config_header = b.addConfigHeader(.{
        .style = .{
            .cmake = std.Build.LazyPath.relative("cmake/config.h.cmake"),
        },
    }, config_values);

    libnfs.addConfigHeader(config_header);

    libnfs.addCSourceFiles(.{ .files = &libnfs_sources, .flags = &.{ "-nostdinc", "-Wno-implicit-function-declaration", "-DHAVE_CONFIG_H" } });
    // @ivanv: not sure if all of these includes are needed
    libnfs.addIncludePath(.{ .path = "mount" });
    libnfs.addIncludePath(.{ .path = "nfs" });
    libnfs.addIncludePath(.{ .path = "nfs4" });
    libnfs.addIncludePath(.{ .path = "nlm" });
    libnfs.addIncludePath(.{ .path = "nsm" });
    libnfs.addIncludePath(.{ .path = "portmap" });
    libnfs.addIncludePath(.{ .path = "rquota" });
    libnfs.addIncludePath(.{ .path = "lib" });
    libnfs.addIncludePath(.{ .path = "include/nfsc" });
    libnfs.addIncludePath(.{ .path = "include" });

    libnfs.addSystemIncludePath(libc.path("picolibc"));
    libnfs.addSystemIncludePath(libc.path("picolibc/newlib/libc/include"));
    libnfs.addSystemIncludePath(libc.path("picolibc/newlib/libc/tinystdio"));
    libnfs.addSystemIncludePath(libc.path("posix/include"));
    // @ivanv: this is weird. Needs investigation. Also depends on
    // autogenerated file 'alltypes.h'
    libnfs.addSystemIncludePath(libc.path("posix/arch/generic/"));
    libnfs.addSystemIncludePath(libc.path("posix/arch/aarch64_sel4/"));

    b.installArtifact(libnfs);
}
